// Builds a self-contained Markdown "interview packet" for a candidate —
// ATS breakdown, strengths/weaknesses, recent activity, and any generated
// interview questions gathered during the session. No external deps;
// downloads client-side via a Blob URL.

function line(label, value) {
  return value != null && value !== '' ? `**${label}:** ${value}\n` : ''
}

export function buildInterviewPacket({ candidate, githubData, repoIndex, extraQuestions = [] }) {
  const name = candidate?.name || githubData?.name || githubData?.username || 'Candidate'
  const parts = [`# Interview packet — ${name}`, '']

  parts.push('## Overview')
  parts.push(line('Role', candidate?.role))
  parts.push(line('Experience', candidate?.expYears != null ? `${candidate.expYears} years` : null))
  parts.push(line('Education', candidate?.education))
  parts.push(line('GitHub', githubData ? `@${githubData.username} · ${githubData.publicRepos} public repos` : null))
  parts.push('')

  if (candidate?.ats) {
    parts.push('## ATS score')
    parts.push(`**${candidate.ats.total}/100** — ${candidate.ats.label}`)
    parts.push('')
    Object.entries(candidate.ats.breakdown || {}).forEach(([k, v]) => parts.push(`- ${k}: ${v}`))
    parts.push('')
  }

  if (candidate?.skills?.length) {
    parts.push('## Skills')
    parts.push(candidate.skills.join(', '))
    parts.push('')
  }

  if (githubData?.languageStats?.length) {
    parts.push('## Languages (GitHub)')
    parts.push(githubData.languageStats.map(l => `${l.name} (${l.percentage}%)`).join(', '))
    parts.push('')
  }

  if (githubData?.contributions?.length) {
    parts.push('## Open source contributions')
    githubData.contributions.slice(0, 8).forEach(c => {
      parts.push(`- [${c.repo}] ${c.kind === 'pull_request' ? 'PR' : 'Issue'} (${c.state}): ${c.title || '—'}`)
    })
    parts.push('')
  }

  if (repoIndex) {
    parts.push('## Repository under review')
    parts.push(`${repoIndex.owner}/${repoIndex.repo}${repoIndex.branch ? ` (${repoIndex.branch})` : ''}`)
    parts.push('')
  }

  const questions = [...extraQuestions]
  if (questions.length) {
    parts.push('## Suggested interview questions')
    questions.forEach((q, i) => parts.push(`${i + 1}. ${q}`))
    parts.push('')
  }

  parts.push('---')
  parts.push(`_Generated by ResumeIQ on ${new Date().toLocaleDateString()}._`)

  return parts.join('\n')
}

function downloadFile(filename, content, mime) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

export function downloadJSON(filename, obj) {
  downloadFile(filename, JSON.stringify(obj, null, 2), 'application/json;charset=utf-8')
}

export function downloadMarkdown(filename, content) {
  downloadFile(filename, content, 'text/markdown;charset=utf-8')
}
